### ISSUE TITLE
documentation question / update needed

### ISSUE THREAD

**Issue by mturktest123** [ros-drivers/nmea_navsat_driver#99]
On this page - https://wiki.ros.org/nmea_navsat_driver under this section  '2. Sample Usage
To get up and running quickly, you can use the following command to start outputting your GPS data onto ROS topics. This assumes your GPS is outputting GGA NMEA sentences, is connected to /dev/ttyUSB0 and is communicating at 38400 baud."

It mentions using the following command to get up and running quickly; but no command is shown.

**Comment by evenator** [comment]
Thanks for pointing this out. It turns out the command was in a block that was being shown based on which ROS version of the wiki page the user was viewing, and it was never updated beyond ROS Kinetic. The command hasn't changed since the original release of the package, so I removed the version logic from the wiki page, and the command is now displayed properly for new versions of ROS.
